#!/bin/bash

read -p "Enter a number: " number

if [ $number -gt 0 ]; then
    echo "Your number is greater than 0"
elif [ $number -lt 0 ]; then
    echo "Your number is lower than 0"
else
    echo "Your number is 0"
fi

exit 0
